### ISSUE TITLE
SIFT Installation Errors 

### ISSUE THREAD

**Issue by TheRoadToDawn** [teamdfir/sift#380]
So I'm trying to install the SIFT Workstation manually. I followed the instructions on the official GitHub page but it fails on the installation of the Workstation. I run 'sudo sift install' and pretty much everything completes apart from quite a lot of errors at the end. My terminal displays:

>> Incomplete due to Failures -- Success: 490, Failure: 52

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: colorama
        SLS: sift.python-packages.colorama
        Run#: 175
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: construct
        SLS: sift.python-packages.construct
        Run#: 176
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: dpapick
        SLS: sift.python-packages.dpapick
        Run#: 177
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: distorm3
        SLS: sift.python-packages.distorm3
        Run#: 178
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: haystack
        SLS: sift.python-packages.haystack
        Run#: 179
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: lxml
        SLS: sift.python-packages.lxml
        Run#: 180
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: undefined
        SLS: sift.python-packages.ioc_writer
        Run#: 181
        Comment: One or more requisite failed: sift.python-packages.lxml.lxml
      - ID: pefile
        SLS: sift.python-packages.pefile
        Run#: 182
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pycoin
        SLS: sift.python-packages.pycoin
        Run#: 183
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
      - ID: pysocks
        SLS: sift.python-packages.pysocks
        Run#: 184
        Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.

Help would be much appreciated. 
Thanks.

**Comment by TheRoadToDawn** [comment]
Let me also mention that I've looked at every related issue people have had about this and I haven't found any solutions.

**Comment by TheRoadToDawn** [comment]
Managed to fix that error but now I'm getting:
>> Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

**Comment by ekristen** [comment]
Looks like somehow pip just didn't get installed properly or hand an error installing.

Is this ubuntu 16.04 or 18.04?

**Comment by TheRoadToDawn** [comment]
It is Ubuntu 16.04

**Comment by TheRoadToDawn** [comment]
Fixed it, turns out pip3 wasnt installed.

**Comment by ekristen** [comment]
Interesting. I’ll check the dependency install order

**Comment by CiscoCapa** [comment]
Hi Erik,

Getting the same error here:

I tried all the documentation possible and I am still having the same issue

Any suggestion?

>>Incomplete due to Failures -- Success: 539, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
